name: Test Workflow



on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  


jobs:
  test:
    environment: my_pdi
    name: Publish from Dev
    runs-on: ubuntu-latest
    # Below line can be used to set conditionals for modifying your pipeline as needed.
    # if: ${{ github.event_name == 'pull_request'}}
    env:
          nowUsername: ${{ secrets.SN_USERNAME }}
          nowSourceInstance: ${{ secrets.SN_DEV_INSTANCE }}
          nowRegularVariable: ${{ vars.TEST}}
          staticVariable: yooo
    steps:
      - name: Test Log
        run: echo "hello! $nowUsername $nowSourceInstance $staticVariable"

      
