name: Test Workflow
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: my_pdi
  nowUsername: ${{ secrets.NOW_USERNAME }}
  nowSourceInstance: ${{ secrets.NOW_CLIENT_INSTANCE }}
  nowRegularVariable: ${{ vars.REPO_VAR }}
  staticVariable: yooo
  


jobs:
  test:
    
    name: Publish from Dev
    runs-on: ubuntu-latest
    environment:
      name: $env_var
          
    steps:
      - name: Test Log
        run: echo "hello! ||| $nowUsername ||| ${{secrets.NOW_CLIENT_INSTANCE}} ||| ${{ vars.REPO_VAR }} ||| ${{vars.TEST}} ||| ${{secrets.REPO_SECRET}}"

      
