name: Test Workflow
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: my_pdi
  


jobs:
  test:
    
    name: Publish from Dev
    runs-on: ubuntu-latest
    environment: my_pdi
    env:
          nowUsername: ${{ secrets.SN_USERNAME }}
          nowSourceInstance: ${{ secrets.SN_DEV_INSTANCE }}
          nowRegularVariable: ${{ vars.TEST }}
          staticVariable: yooo
    steps:
      - name: Test Log
        run: echo "hello! $nowUsername $nowSourceInstance $staticVariable $env_var he mad"

      
