name: Test Workflow
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
      environment:
        type: environment

env:
  env_var: my_pdi
  
jobs:
  test:
    
    name: Publish from Dev
    runs-on: ubuntu-latest
    environment:
      name: ${{github.event.inputs.environment}}
    env:
      nowUsername: ${{ secrets.NOW_USERNAME }}
      nowSourceInstance: ${{ secrets.NOW_CLIENT_INSTANCE }}
      nowRegularVariable: ${{ vars.REPO_VAR }}
      staticVariable: yooo
    steps:
      - name: Test Log
        run: echo "hello! ||| $nowUsername ||| ${{secrets.NOW_CLIENT_INSTANCE}} ||| ${{ vars.REPO_VAR }} ||| ${{vars.TEST}} ||| ${{secrets.REPO_SECRET}}"
      - name: Log Variables
        run: echo "${{toJSON(vars)}}"
      - name: Log Secrets
        run: echo "${{toJSON(secrets)}}"
      - name: What is github
        run: echo "${{toJSON(github)}}"


      
